apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-frontend
  namespace: arsanandha
  labels:
    app: ap-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap-frontend
  template:
    metadata:
      name: ap-frontend
      labels:
        app: ap-frontend
    spec:
      imagePullSecrets:
        - name: arsanandha-frontend-repo
      containers:
        - name: ap-frontend
          image: registry.gitlab.com/arsanandha.ap/ap-frontend/ap-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: arsanandha-frontend-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ap-frontend-service
  name: ap-frontend-service
  namespace: arsanandha
spec:
  selector:
    app: ap-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: ap-port-3000
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-api-ingress-route
  namespace: arsanandha
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`arsanandha.xyz`) && PathPrefix(`/`)"
      kind: Rule
      services:
        - name: ap-frontend-service
          port: 3000
          passHostHeader: true
      middlewares:
        - name: arsanandha-xyz-frontend-header
  tls:
    certResolver: letsencrypt
    options:
      name: arsanandha-tls-options
      namespace: arsanandha
    domains:
      - main: arsanandha.xyz
