apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-frontend
  labels:
    app: ap-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap-frontend
  template:
    metadata:
      name: ap-frontend
      labels:
        app: ap-frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ap-frontend
          image: registry.gitlab.com/arsanandha.ap/ap-frontend/ap-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ap-frontend-service
  name: ap-frontend-service
spec:
  selector:
    app: ap-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: ap-port-3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ap-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: arsanandha.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
                service:
                  name: ap-frontend-service
                  port:
                    number: 3000
  tls:
    - hosts:
        - arsanandha.xyz
      secretName: arsanandha