apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-frontend
  namespace: arsanandha
  labels:
    app: ap-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap-frontend
  template:
    metadata:
      name: ap-frontend
      labels:
        app: ap-frontend
    spec:
      imagePullSecrets:
        - name: arsanandha-frontend-repo
      containers:
        - name: ap-frontend
          image: registry.gitlab.com/arsanandha.ap/ap-frontend/ap-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ap-frontend-service
  name: ap-frontend-service
  namespace: arsanandha
spec:
  selector:
    app: ap-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: ap-port-3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ap-frontend-ingress
  namespace: arsanandha
spec:
  rules:
    - host: arsanandha.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ap-frontend-service
                port:
                  number: 3000
  tls:
    - hosts:
        - arsanandha.xyz
      secretName: arsanandha-xyz