apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "arsanandha-frontend.labels" . | nindent 4 }}
data:
  {{ if .Values.applicationData.nuxtPublicAPIURL }}
  NUXT_PUBLIC_API_URL: "{{ .Values.applicationData.nuxtPublicAPIURL }}"
  {{ end }}
  {{ if .Values.applicationData.azureADRedirectURI }}
  AZ_TENANT_ID: {{ .Values.applicationData.azureADTenantId }}
  {{ end }}
  {{ if .Values.applicationData.azureADClientId }}
  AZ_CLIENT_ID: {{ .Values.applicationData.azureADClientId }}
  {{ end }}
  {{ if .Values.applicationData.azureADAudience }}
  AZ_AUDIENCE: {{ .Values.applicationData.azureADAudience }}
  {{ end }}
  {{ if .Values.applicationData.azureADRedirectURI }}
  AZ_REDIRECT_URI: {{ .Values.applicationData.azureADRedirectURI }}
  {{ end }}