apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "arsanandha-frontend.labels" . | nindent 4 }}
data:
  {{ if .Values.applicationData.nuxtPublicAPIURL }}
  NUXT_PUBLIC_API_URL: "{{ .Values.applicationData.nuxtPublicAPIURL }}"
  {{ end }}
