apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "arsanandha-frontend.fullname" . }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prd
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - {{ .Values.ingressData.domain }}
      secretName: arsanandha-xyz-domain-cert-prod
  rules:
    - host: {{ .Values.ingressData.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "arsanandha-frontend.fullname" . }}-service
                port:
                  number: 3000