apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  NUXT_API_KEY: {{ .Values.credentials.nuxtAPIKey | b64enc }}
  NUXT_AZ_CLIENT_SECRET: {{ .Values.credentials.azureADClientSecret | b64enc }}
