apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  NUXT_API_KEY: {{ .Values.credentials.nuxtAPIKey | b64enc }}
  NUXT_AUTH_STRATEGIES_AZURE_AD_CLIENT_SECRET: {{ .Values.credentials.azureADClientSecret | b64enc }}
  NUXT_BREWER_API_KEY: {{ .Values.credentials.nuxtBrewerAPIKey | b64enc }}
