apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "arsanandha-frontend.fullname" . }}-virtual-service
spec:
  hosts:
    - {{ .Values.ingressData.domain }}
  gateways:
    - istio-system/gateway-prod
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "arsanandha-frontend.fullname" . }}-service
            port:
              number: 3000
          headers:
            response:
              add:
                X-FRONTEND-VERSION: {{ .Chart.AppVersion }}
                X-APPLICATION-BUILD-NAME: {{ .Values.codename }}